FormsDemo/FormsDemo/Models/Zombie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FormsDemo.Models
{
    public class Zombie
    {
        public string Name { get; set; }
        public string ZedType { get; set; }
        public int HoursUndead { get; set; }

        public override string ToString()
        {
            return $"{Name}({ZedType}) - {HoursUndead} hour(s) undead";
        }
    }
}

FormsDemo/FormsDemo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FormsDemo.Models;
using Microsoft.AspNetCore.Mvc;

namespace FormsDemo.Controllers
{
    public class HomeController : Controller
    {
        private static List<Zombie> zombies = new List<Zombie>();
        public IActionResult Index()
        {
            return View(zombies);
        }

        public static void AddZombie(Zombie zombie)
        {
            zombies.Add(zombie);
        }
    }
}

FormsDemo/FormsDemo/Controllers/ZombieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FormsDemo.Models;
using Microsoft.AspNetCore.Mvc;

namespace FormsDemo.Controllers
{
    public class ZombieController : Controller
    {
        [HttpGet]//permission gate
        public IActionResult CreateZombie()
        {
            //if the query string contains an index value, add it to ViewBag.Index
            //Otherwise, set ViewBag.Index to -1
            ViewBag.Index = -1;
            return View();
        }
        //[HttpPost]
        //public IActionResult CreateZombie(string name, string zedType, int hoursUndead)
        //{
        //    Zombie zombie = new Zombie() { Name = name, ZedType = zedType, HoursUndead = hoursUndead };
        //    HomeController.AddZombie(zombie);
        //    return RedirectToAction("Index", "Home");
        //}
        [HttpPost]
        public IActionResult CreateZombie(Zombie zombie)
        {
            //int hours = int.Parse(Request.Form["hoursUndead"]);//get data from form
            //Zombie zombie = new Zombie() { Name = name, ZedType = zedType, HoursUndead = hoursUndead };
            HomeController.AddZombie(zombie);
            return RedirectToAction("Index", "Home");
        }
    }
}

FormsDemo/FormsDemo/Views/Home/Index.cshtml
@using FormsDemo.Models
@model IEnumerable<Zombie>
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <a asp-action="CreateZombie" asp-controller="Zombie">Create Zombie</a>

    @if (Model.Count() > 0||Model!=null)
    {
        <ul>
            @foreach (Zombie zed in Model)
            {
                if (zed != null)
                {
                    <li>
                        @zed.ToString()
                    </li>
                }
                else
                {
                    <li>Null Zed</li>
                }
            }
        </ul>
    }
    else
    {
        <h2>There are no Zeds to display</h2>
    }
</body>
</html>

FormsDemo/FormsDemo/Views/Zombie/CreateZombie.cshtml
@using FormsDemo.Models
@model Zombie

@{ 
    int index = ViewBag.Index ?? -2;
    //?? null coalescer use value if not null else use second value
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CreateZombie</title>
</head>
<body>
    <form method="post" action="~/Zombie/CreateZombie">
        <input type="hidden" name="index" value="@index"/><br/>
        <input type="text" name="name" placeholder="Zombie Name"/><br/>
        <input type="text" name="zedType" placeholder="Zombie Type"/><br/>
        <input type="number" min="0" name="hoursUndead" placeholder="Hours Undead"/><br/>
        <input type="submit" value="Create Zombie"/>
    </form>
</body>
</html>